name: create-version
on:
  push:
    branches:
      - dan-updates

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: dan-updates

      - name: Configure Github credentials
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Bump version
        run: |
          echo "bumping version on branch $(git branch --show-current)"
          npm version patch
          # git push

      - name: Run build script
        run: |
          npm run build

      - name: Set new version
        run: |
          NEW_VERSION_NUMBER=$(node -e "console.log(require('./package.json').version);")
          echo "::set-env name=NEW_VERSION_NUMBER::$NEW_VERSION_NUMBER"

      - name: Package distribution
        run: |
          BUILDS_DIR=builds
          mkdir -p $BUILDS_DIR

          echo NEW_VERSION_NUMBER = $NEW_VERSION_NUMBER

          cd dist
          zip -r ../$BUILDS_DIR/$NEW_VERSION_NUMBER.zip .
          cd ..

          ls -alrt

      - name: Commit new version and push
        run: |
          git add .
          git commit -m 'new version - $NEW_VERSION_NUMBER'
          git push