name: create-version
on:
  push:
    branches:
      - dan-updates

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: dan-updates

      - name: Configure Github credentials
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Bump version
        run: |
          echo "bumping version on branch $(git branch --show-current)"
          npm version patch
          git status

      - name: Get new version
        run: |
          NEW_VERSION=$(node -e "console.log(require('./package.json').version);")
          echo NEW_VERSION = $NEW_VERSION

      - name: Run build script
        run: |
          npm run build

      - name: Zip distribution
        run: |
          cd dist
          zip -r ../new_version.zip .
          cd ..
          ls -alrt