name: create-version
on:
  push:
    branches:
      - master

jobs:
  build-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Configure Github credentials
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Bump version
        id: new_version
        run: |
          # increment package.json version
          npm version patch

          # get the new version from package.json
          NEW_VERSION_NUMBER=$(node -e "console.log(require('./package.json').version);")
          echo "new version = $NEW_VERSION_NUMBER"

          # increment manifest.json version
          sed -i.bak -E 's/("version"):\s*"[0-9.]*"/"version": "'${NEW_VERSION_NUMBER}'"/g' ./public/manifest.json
          
          # set the new version as an output of this step (github syntax)
          echo "::set-output name=NEW_VERSION_NUMBER::$NEW_VERSION_NUMBER"

      - name: Run build script
        run: |
          npm run build

      - name: Package distribution
        run: |
          # get new version number
          VER=${{ steps.new_version.outputs.NEW_VERSION_NUMBER }}
          
          # create builds directory
          BUILDS_DIR=builds
          mkdir -p $BUILDS_DIR

          # create a file name from the new version
          FILENAME=$VER.zip

          # create deployment package and place in builds directory
          cd dist
          zip -r ../$BUILDS_DIR/$FILENAME .
          cd ..

      - name: Commit new version and push
        run: |
          # get new version number
          VER=${{ steps.new_version.outputs.NEW_VERSION_NUMBER }}

          # commit and push changes
          git add .
          git commit -m "new version - $VER"
          git push