name: create-version
on:
  push:
    branches:
      - dan-updates

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: dan-updates
      - name: Get current version
        run: |
          
      - name: Run build script
        run: |
          pwd
          node -v

          npm run build
      - name: Zip distribution
        run: |
          cd dist
          zip -r ../new_version.zip .
          cd ..
          ls -alrt